// <auto-generated />
using System;
using FunktsiooniUurimine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunktsiooniUurimine.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FunktsiooniUurimine.Models.FunktsiooniUurimine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ekstreemumid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KriitilisedPunktid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LuodudAeg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maaramispiirkond")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nullkohad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tuletis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FunktsiooniUurimised");
                });
#pragma warning restore 612, 618
        }
    }
}
